### ISSUE TITLE
TODO - update and new examples to import from the deployed package

### ISSUE THREAD

**Issue by dtq-three** [dtq-three/issue-sync-test#5]
Issue created by:biancode

# Server
- [ ] server
- [ ] demo server
- [ ] flex-server
- [ ] secured server with user logins
- [ ] server with own types
- [ ] ASO server

# Client
- [ ] client read
- [ ] client write
- [ ] secured client with user login
- [ ] client flex connector
- [ ] listener and monitoring
- [ ] events and alarms
- [ ] browser
- [ ] crawler
- [ ] simple method call
- [ ] complex method call

# Response Tools
- [ ] response
- [ ] result filter

# Discovery
- [ ] local

# Demos
- [ ] all in one demo
